User.create!([
  {username: "SerenaWilliams", email: "serenawilliams@gmail.com", session_token: "D2BHwQ7_S-8J0Aq6sQB5zXE", password_digest: "$2a$10$e6RKTKsKpwESh75no1Ie2u0UZpMQUwtDu3w7KU3Pmf2sdA3ae5GYq", image_url: "https://specials-images.forbesimg.com/imageserve/575706a4a7ea43396db27353/416x416.jpg?background=000000&cropX1=138&cropX2=676&cropY1=126&cropY2=664"},
  {username: "Alberto", email: "albert@gmail.com", session_token: "UvApUzYg-X1QTSKq78O2Zm0", password_digest: "$2a$10$3Q9E5yvCJw0JydGJA3qlg.hH5eP6l6/uJTfqBDKyAj6dWJJh0nNrq", image_url: "https://usatftw.files.wordpress.com/2017/07/kobe-champion.jpg"},
  {username: "HelloGuest", email: "bestguest@gmail.com", session_token: "1P-EkO2Rj9IiqsK-hhBFW8M", password_digest: "$2a$10$q6Y5qAyRSBnEXyaYRfousu6vNzC9Ag6wyieqEOgZ9GlFyN/lkuzTK", image_url: "https://www.limestone.edu/sites/default/files/user.png"},
  {username: "MiaHamm", email: "miahamm@gmail.com", session_token: "53uxAYT8fqhri37dul9XnB8", password_digest: "$2a$10$FvpXzGwpqL8ZqPX9OPUDGe0KI/vHrkAmlRo.TA2deo0de2wHGP.72", image_url: "https://static1.squarespace.com/static/52f13ae1e4b08a02b16034fb/t/52fd6734e4b09b324c795621/1392338742015/Mia_Hamm.jpg?format=2500w"},
  {username: "BertShin", email: "bertshin@gmail.com", session_token: "SBUbOXxR9tCuzaKH5jhsaNE", password_digest: "$2a$10$WzH3D5ftUJUtRyi4K.KJZONGOYfEtYaM976M1amxE/QKa6I8e93zu", image_url: "https://pbs.twimg.com/profile_images/950664597366714369/M4PmYTBN.jpg"}
  ])
  
Post.create!([
  {title: "The person that said winning isn’t everything", user_id: 1, description: "Mia Hamm", image_url: nil, likes: nil, content: "never won anything", content_type: "Quote"},
  {title: "Still one of the best dunks of all time!", user_id: 2, description: "By KB The GOAT", image_url: "https://media.giphy.com/media/VvZSI1pH1b2Ra/giphy.gif", likes: nil, content: nil, content_type: "Text"},
  {title: "LETS GO!!!", user_id: 1, description: "Who's ready for the Super Bowl??", image_url: "https://media.giphy.com/media/l4pT5DCioJzFw10oo/giphy.gif", likes: nil, content: nil, content_type: "Text"},
  {title: "Steph a fool LOL", user_id: 3, description: nil, image_url: "https://media.giphy.com/media/3oEjHIPW937PZ7zzLq/giphy.gif", likes: nil, content: nil, content_type: "Text"},
  {title: "Check this sick MJ gif!", user_id: 2, description: "Who did dis", image_url: "https://media.giphy.com/media/zAYZOtH5OMhuU/giphy.gif", likes: nil, content: nil, content_type: "Text"},
  {title: "Funniest thing I've seen all day LOL", user_id: 2, description: nil, image_url: "https://media.giphy.com/media/xT9IguGd9sn4dIbaiQ/giphy.gif", likes: nil, content: nil, content_type: "Text"},
  {title: "Me when I'm on a roll at work", user_id: 2, description: nil, image_url: "https://media.giphy.com/media/3otPorZ08nPuaZfoeA/giphy.gif", likes: nil, content: nil, content_type: "Text"},
  {title: "I don't want to be Michael Jordan...", user_id: 2, description: nil, image_url: nil, likes: nil, content: "I don't want to be Michael Jordan, I want to be Kobe Bryant", content_type: "Quote"},
  {title: "Seriously what debate is there?", user_id: 2, description: nil, image_url: nil, likes: nil, content: "Why is there such a debate between who's the GOAT? Kobe is obviously the goat.. #PplgottaRecognize #5>6 #24>23", content_type: "Text"},
  {title: "startin young~", user_id: 3, description: "", image_url: "https://static1.squarespace.com/static/54b4319ee4b02eb93428f3d1/54b5a090e4b0bb2b0191e74c/54b68851e4b05e2e7fb7fb31/1421248595522/project-play-young-girl-baseball-pitcher.jpg", likes: nil, content: nil, content_type: "Photo"},
  {title: "Classic Matchup", user_id: 3, description: "Red Vs Blue", image_url: "http://cdn.playbuzz.com/cdn/ee99c687-7a57-4c9b-bcd7-c70357122916/d3a4eb82-d74f-45dd-8e3e-915e10ac2b07.jpg", likes: nil, content: nil, content_type: "Photo"},
  {title: "Hit a new PR this week!", user_id: 1, description: "300 CLUB BABY!", image_url: nil, likes: nil, content: "Bumped up from 285 to 300 bench!", content_type: "Text"},
  {title: "THIS WEEKEND", user_id: 1, description: "Who's Down.", image_url: "https://media.giphy.com/media/i4msiqM6qQaU8/giphy.gif", likes: nil, content: "", content_type: "Text"},
  {title: "Hi", user_id: 1, description: "", image_url: "https://media2.giphy.com/media/xUNd9QBCkAPWMttkAg/200.gif?cid=e1bb72ff5a7b9317346a354a63c8c7bf", likes: nil, content: nil, content_type: "GIF"},
  {title: "Champions keep playing", user_id: 1, description: "Billie Jean King", image_url: nil, likes: nil, content: "until they get it right", content_type: "Quote"},
  {title: "I did it :)", user_id: 5, description: "", image_url: "https://media1.giphy.com/media/qkIFAzrOBrYvm/200.gif?cid=e1bb72ff5a7ba38d6b486a2f676b7a5d", likes: nil, content: nil, content_type: "GIF"},
  {title: "Fumblr", user_id: 1, description: "", image_url: "https://media2.giphy.com/media/Ch3B2ty7gY7HW/200.gif?cid=e1bb72ff5a7968896946535532f3bd0a", likes: nil, content: nil, content_type: "GIF"},
  {title: "To Fumble or Not to Fumble", user_id: 3, description: "", image_url: nil, likes: nil, content: "that is the question", content_type: "Quote"},
  {title: "I am a member of a team", user_id: 5, description: "Mia Hamm AKA me :)", image_url: nil, likes: nil, content: "and I rely on the team, I defer to it and sacrifice for it, because the team, not the individual, is the ultimate champion.", content_type: "Quote"},
  {title: "Failure happens all the time", user_id: 5, description: "Mia Hamm.. Again me :)", image_url: nil, likes: nil, content: "It happens every day in practice. What makes you better is how you react to it.", content_type: "Quote"},
  {title: "Such Swag from our Junior US Team!", user_id: 5, description: "", image_url: "https://media1.giphy.com/media/hRDu4lNEfUm76/200.gif?cid=e1bb72ff5a7ba421473762336f251073", likes: nil, content: nil, content_type: "GIF"},
  {title: "This is a test quote", user_id: 1, description: "", image_url: nil, likes: nil, content: "What a great quote", content_type: "Quote"},
  {title: "Ya'll know who's bouta win the Dunk Contest", user_id: 1, description: "", image_url: "https://media.giphy.com/media/12ZV3oW1llVG0M/giphy.gif", likes: nil, content: "", content_type: "Text"},
  {title: "I hated every minute of training", user_id: 1, description: "Muhammed Ali", image_url: nil, likes: nil, content: " but I said, ‘Don’t quit. Suffer now and live the rest of your life as a champion.", content_type: "Quote"},
  {title: "I’ve missed more than 9000 shots in my career", user_id: 1, description: "Michael Jordan", image_url: nil, likes: nil, content: "I’ve lost almost 300 games. 26 times, I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.”", content_type: "Quote"},
  {title: "When your friend says they have food for you.. but they ate it", user_id: 1, description: "", image_url: "https://media.giphy.com/media/11H9nN7VS1bhkI/giphy.gif", likes: nil, content: "", content_type: "Text"},
  {title: "TFW your serve doesn't fly", user_id: 4, description: "sad life", image_url: "https://media.giphy.com/media/26xBJXRsehokyUSME/giphy.gif", likes: nil, content: "", content_type: "Text"},
  {title: "I've had to learn to fight my whole life", user_id: 4, description: "Serena Williams AKA myself", image_url: nil, likes: nil, content: "got to learn to keep smiling. If you smile, things will work out", content_type: "Quote"},
  {title: "Hittin 3's @ the 24 like", user_id: 3, description: "bang bang", image_url: "https://media.giphy.com/media/3ohs4xFl0wj0FehtfO/giphy.gif", likes: nil, content: "", content_type: "Text"},
  {title: "GOAT", user_id: 3, description: "", image_url: "https://media.giphy.com/media/L5ohDduqx0dwY/giphy.gif", likes: nil, content: "", content_type: "Text"}
])
